import { Metadata } from "next";

export const metadata: Metadata = {
    title: "App Create By Tuấn Dev",
    description: "Generated by create next app",
};
export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <head>
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>{children}</body>
        </html>
    );
}
